apiVersion: batch/v1
kind: Job
metadata:
  name: offline-campaign-job
spec:
  # ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: offline-campaign-job
        image: "#!IMAGE_VALUE!#"
        imagePullPolicy: Never
        command: ["/bin/bash"]
        args:
        - -c
        - source /opt/auth/virtualenv/v1/bin/activate && python -m auth.management.commands.aws_config && python3 manage.py offline_campaign --reason "#!REASON!#" --file_name "#!FILE_NAME!#"
      restartPolicy: Never
  backoffLimit: 0
